package pe.edu.uni.autoventas.view;

import pe.edu.uni.autoventas.controller.EmpleadoCrudController;
import pe.edu.uni.autoventas.model.EmpleadoModel;
import pe.edu.uni.autoventas.util.Mensaje;
import pe.edu.uni.autoventas.util.Session;
import pe.edu.uni.autoventas.util.UtilView;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class EditarEmpleadoView extends javax.swing.JDialog {

	private String accion;
	private EmpleadoModel record;
	
    /** Creates new form EditarEmpleadoView */
    public EditarEmpleadoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
		  this.setLocationRelativeTo(null);
    }

	public void setAccion(String accion) {
		this.accion = accion;
		this.setTitle(accion + " Empleado");
		this.setEditStatus();
	}
	
	private void setEditStatus(){
		txtApellidos.setEnabled(!accion.equals(UtilView.CRUD_ELIMINAR));
		txtNombres.setEnabled(!accion.equals(UtilView.CRUD_ELIMINAR));
		txtDni.setEnabled(!accion.equals(UtilView.CRUD_ELIMINAR));
		txtTelefono.setEnabled(!accion.equals(UtilView.CRUD_ELIMINAR));
		txtCorreo.setEnabled(!accion.equals(UtilView.CRUD_ELIMINAR));
		txtUsuario.setEnabled(!accion.equals(UtilView.CRUD_ELIMINAR));
		txtRol.setEnabled(!accion.equals(UtilView.CRUD_ELIMINAR));
		txtClave.setEnabled(accion.equals(UtilView.CRUD_NUEVO));
	}
	
	public void setRecord(EmpleadoModel record){
		this.record = record;
		pintarRecord();
	}
	
	private void pintarRecord(){
		txtId.setText(record.getId() + "" );
		txtApellidos.setText(record.getApellido());
		txtNombres.setText(record.getNombre());
		txtDni.setText(record.getDni());
		txtTelefono.setText(record.getTelefono());
		txtCorreo.setText(record.getCorreo());
		txtRol.setText(record.getRol() + "");
		txtUsuario.setText(record.getUsuario());
		txtClave.setText(record.getClave());
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtId = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtApellidos = new javax.swing.JTextField();
      txtNombres = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      txtDni = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      txtTelefono = new javax.swing.JTextField();
      txtCorreo = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      txtRol = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      txtUsuario = new javax.swing.JTextField();
      jLabel8 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      txtClave = new javax.swing.JPasswordField();
      jPanel2 = new javax.swing.JPanel();
      btnCancelar = new javax.swing.JButton();
      btnGrabar = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("{ACCION} EMPLEADO");

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 102, 204))); // NOI18N

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(102, 102, 102));
      jLabel1.setText("Código:");

      txtId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtId.setForeground(new java.awt.Color(102, 102, 102));
      txtId.setDisabledTextColor(new java.awt.Color(0, 153, 204));
      txtId.setEnabled(false);

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(102, 102, 102));
      jLabel2.setText("Apellidos:");

      txtApellidos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtApellidos.setForeground(new java.awt.Color(102, 102, 102));
      txtApellidos.setDisabledTextColor(new java.awt.Color(0, 153, 204));

      txtNombres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtNombres.setForeground(new java.awt.Color(102, 102, 102));
      txtNombres.setDisabledTextColor(new java.awt.Color(0, 153, 204));

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(102, 102, 102));
      jLabel3.setText("Nombres:");

      jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(102, 102, 102));
      jLabel4.setText("DNI:");

      txtDni.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtDni.setForeground(new java.awt.Color(102, 102, 102));
      txtDni.setDisabledTextColor(new java.awt.Color(0, 153, 204));

      jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(102, 102, 102));
      jLabel5.setText("Teléfono");

      txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtTelefono.setForeground(new java.awt.Color(102, 102, 102));
      txtTelefono.setDisabledTextColor(new java.awt.Color(0, 153, 204));

      txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtCorreo.setForeground(new java.awt.Color(102, 102, 102));
      txtCorreo.setDisabledTextColor(new java.awt.Color(0, 153, 204));

      jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel6.setForeground(new java.awt.Color(102, 102, 102));
      jLabel6.setText("Correo:");

      txtRol.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtRol.setForeground(new java.awt.Color(102, 102, 102));
      txtRol.setDisabledTextColor(new java.awt.Color(0, 153, 204));

      jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel7.setForeground(new java.awt.Color(102, 102, 102));
      jLabel7.setText("Rol:");

      txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
      txtUsuario.setDisabledTextColor(new java.awt.Color(0, 153, 204));

      jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel8.setForeground(new java.awt.Color(102, 102, 102));
      jLabel8.setText("Usuario:");

      jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel9.setForeground(new java.awt.Color(102, 102, 102));
      jLabel9.setText("Clave:");

      txtClave.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtClave.setDisabledTextColor(new java.awt.Color(0, 153, 204));

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtClave)))
            .addContainerGap(63, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtDni, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtRol, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtClave, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 102, 204))); // NOI18N

      btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
      btnCancelar.setForeground(new java.awt.Color(102, 102, 102));
      btnCancelar.setText("Cancelar");
      btnCancelar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelarActionPerformed(evt);
         }
      });

      btnGrabar.setBackground(new java.awt.Color(153, 255, 255));
      btnGrabar.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
      btnGrabar.setForeground(new java.awt.Color(102, 102, 102));
      btnGrabar.setText("Grabar");
      btnGrabar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnGrabarActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(59, Short.MAX_VALUE)
            .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(101, 101, 101))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(38, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      this.dispose();
   }//GEN-LAST:event_btnCancelarActionPerformed

   private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
      // Variables
		record = new EmpleadoModel();
		// Proceso
		try {
			// Datos
			record.setId(Integer.parseInt(txtId.getText()));
			record.setApellido(txtApellidos.getText());
			record.setNombre(txtNombres.getText());
			record.setDni(txtDni.getText());
			record.setCorreo(txtCorreo.getText());
			record.setTelefono(txtTelefono.getText());
			record.setRol(Integer.parseInt(txtRol.getText()));
			record.setUsuario(txtUsuario.getText());
			record.setClave(String.valueOf(txtClave.getPassword()));
			// Proceso
			EmpleadoCrudController control = new EmpleadoCrudController();
			switch(this.accion){
				case UtilView.CRUD_NUEVO:
					control.insert(record);
					break;
				case UtilView.CRUD_EDITAR:
					control.update(record);
					break;
				case UtilView.CRUD_ELIMINAR:
					control.delete(record.getId());
					break;
			}
			// Cerrar formulario
			Session.put("bean", record);
			this.dispose();
			Mensaje.info(this, "Proceso ejecutado correctamente.");
		} catch (Exception e) {
			Mensaje.error(this, e.getMessage());
		}
   }//GEN-LAST:event_btnGrabarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarEmpleadoView dialog = new EditarEmpleadoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCancelar;
   private javax.swing.JButton btnGrabar;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JTextField txtApellidos;
   private javax.swing.JPasswordField txtClave;
   private javax.swing.JTextField txtCorreo;
   private javax.swing.JTextField txtDni;
   private javax.swing.JTextField txtId;
   private javax.swing.JTextField txtNombres;
   private javax.swing.JTextField txtRol;
   private javax.swing.JTextField txtTelefono;
   private javax.swing.JTextField txtUsuario;
   // End of variables declaration//GEN-END:variables

}
