package pe.edu.uni.autoventas.view;

import javax.swing.JInternalFrame;
import pe.edu.uni.autoventas.model.EmpleadoModel;
import pe.edu.uni.autoventas.util.Session;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class MainView extends javax.swing.JFrame {

	/**
	 * Creates new form MainView
	 */
	public MainView() {
		initComponents();
		establecerTitulo();
		this.setLocationRelativeTo(null);
		this.setExtendedState(MAXIMIZED_BOTH);
	}

	private void establecerTitulo() {
		EmpleadoModel empleado = (EmpleadoModel) Session.get("USUARIO");
		String titulo = "EUREKA SOLUTION (Usuario:" + empleado.getUsuario() + ")";
		this.setTitle(titulo);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      desktopPane = new javax.swing.JDesktopPane();
      menuBar = new javax.swing.JMenuBar();
      fileMenu = new javax.swing.JMenu();
      exitMenuItem = new javax.swing.JMenuItem();
      menuUtil = new javax.swing.JMenu();
      menuUtilCambiarClave = new javax.swing.JMenuItem();
      helpMenu = new javax.swing.JMenu();
      contentMenuItem = new javax.swing.JMenuItem();
      aboutMenuItem = new javax.swing.JMenuItem();
      menuTabla = new javax.swing.JMenu();
      menuTablaProductos = new javax.swing.JMenuItem();
      menuTablaClientes = new javax.swing.JMenuItem();
      menuTablaEmpleados = new javax.swing.JMenuItem();
      menuTablaRutas = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      fileMenu.setMnemonic('f');
      fileMenu.setText("File");

      exitMenuItem.setMnemonic('x');
      exitMenuItem.setText("Exit");
      exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            exitMenuItemActionPerformed(evt);
         }
      });
      fileMenu.add(exitMenuItem);

      menuBar.add(fileMenu);

      menuUtil.setText("Util");

      menuUtilCambiarClave.setText("Cambiar clave");
      menuUtil.add(menuUtilCambiarClave);

      menuBar.add(menuUtil);

      helpMenu.setMnemonic('h');
      helpMenu.setText("Help");

      contentMenuItem.setMnemonic('c');
      contentMenuItem.setText("Contents");
      helpMenu.add(contentMenuItem);

      aboutMenuItem.setMnemonic('a');
      aboutMenuItem.setText("About");
      helpMenu.add(aboutMenuItem);

      menuBar.add(helpMenu);

      menuTabla.setText("Tabla");

      menuTablaProductos.setText("Productos");
      menuTabla.add(menuTablaProductos);

      menuTablaClientes.setText("Clientes");
      menuTabla.add(menuTablaClientes);

      menuTablaEmpleados.setText("Empleados");
      menuTablaEmpleados.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuTablaEmpleadosActionPerformed(evt);
         }
      });
      menuTabla.add(menuTablaEmpleados);

      menuTablaRutas.setText("Rutas");
      menuTablaRutas.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuTablaRutasActionPerformed(evt);
         }
      });
      menuTabla.add(menuTablaRutas);

      menuBar.add(menuTabla);

      setJMenuBar(menuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
		 System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

   private void menuTablaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablaEmpleadosActionPerformed
      mostrarForm(MantEmpleadosView.class);
   }//GEN-LAST:event_menuTablaEmpleadosActionPerformed

   private void menuTablaRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablaRutasActionPerformed
     mostrarForm(MantRutasView.class);
   }//GEN-LAST:event_menuTablaRutasActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainView().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenuItem aboutMenuItem;
   private javax.swing.JMenuItem contentMenuItem;
   private javax.swing.JDesktopPane desktopPane;
   private javax.swing.JMenuItem exitMenuItem;
   private javax.swing.JMenu fileMenu;
   private javax.swing.JMenu helpMenu;
   private javax.swing.JMenuBar menuBar;
   private javax.swing.JMenu menuTabla;
   private javax.swing.JMenuItem menuTablaClientes;
   private javax.swing.JMenuItem menuTablaEmpleados;
   private javax.swing.JMenuItem menuTablaProductos;
   private javax.swing.JMenuItem menuTablaRutas;
   private javax.swing.JMenu menuUtil;
   private javax.swing.JMenuItem menuUtilCambiarClave;
   // End of variables declaration//GEN-END:variables

	private void mostrarForm(Class<?> aClass) {
		try {
			// Variable de control
			JInternalFrame view = null;
			// Buscar instancia
			for (JInternalFrame form : desktopPane.getAllFrames()) {
				if (aClass.isInstance(form)) {
					view = form;
					break;
				}
			}
			// Crear instancia
			if (view == null) {
				view = (JInternalFrame) aClass.getConstructor().newInstance();
				desktopPane.add(view);
				view.setVisible(true);
			}
			view.setMaximum(true);
			view.setSelected(true);
		} catch (Exception e) {
		}
	}

}
