package pe.edu.uni.autoventas.view;

import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFDataFormat;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import org.apache.poi.ss.usermodel.CellType;
import pe.edu.uni.autoventas.controller.EmpleadoCrudController;
import pe.edu.uni.autoventas.model.EmpleadoModel;
import pe.edu.uni.autoventas.util.Mensaje;
import pe.edu.uni.autoventas.util.Session;
import pe.edu.uni.autoventas.util.UtilView;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class MantEmpleadosView extends javax.swing.JInternalFrame {
	
	private List<EmpleadoModel> lista = new ArrayList<>();

    /** Creates new form MantEmpleadosView */
    public MantEmpleadosView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtDni = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtApellidos = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      txtNombres = new javax.swing.JTextField();
      btnBuscar = new javax.swing.JButton();
      btnNuevo = new javax.swing.JButton();
      btnEditar = new javax.swing.JButton();
      btnBorrar = new javax.swing.JButton();
      btnExcel = new javax.swing.JButton();
      btnPDF = new javax.swing.JButton();
      btnBuscar6 = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblDatos = new javax.swing.JTable();

      setClosable(true);
      setIconifiable(true);
      setMaximizable(true);
      setTitle("MANTENIMIENTO DE EMPLEADOS");

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 102, 255))); // NOI18N

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel1.setText("DNI");

      txtDni.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel2.setText("Apellidos");

      txtApellidos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel3.setText("Nombres");

      txtNombres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

      btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
      btnBuscar.setToolTipText("Consultar empleados");
      btnBuscar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBuscarActionPerformed(evt);
         }
      });

      btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
      btnNuevo.setToolTipText("Agregar nuevo empleado.");
      btnNuevo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnNuevoActionPerformed(evt);
         }
      });

      btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
      btnEditar.setToolTipText("Modificar empleado actual.");
      btnEditar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEditarActionPerformed(evt);
         }
      });

      btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tacho.png"))); // NOI18N
      btnBorrar.setToolTipText("Borra el registro seleccionado");
      btnBorrar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBorrarActionPerformed(evt);
         }
      });

      btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.png"))); // NOI18N
      btnExcel.setToolTipText("Exporta a Excel la lista actual.");
      btnExcel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnExcelActionPerformed(evt);
         }
      });

      btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pdf.png"))); // NOI18N
      btnPDF.setToolTipText("Exporta a PDF la lista actual.");

      btnBuscar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
      btnBuscar6.setToolTipText("Cierra el formulario.");
      btnBuscar6.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBuscar6ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnBuscar)
            .addGap(9, 9, 9)
            .addComponent(btnNuevo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnEditar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnBorrar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnExcel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnPDF)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnBuscar6)
            .addContainerGap(49, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(9, 9, 9)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                     .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btnBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btnExcel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btnPDF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btnBuscar6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                     .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(jPanel1Layout.createSequentialGroup()
                     .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 102, 255))); // NOI18N

      tblDatos.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "ID", "APELLIDOS", "NOMBRES", "DNI", "TELEFONO", "CORREO"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
         };
         boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      tblDatos.setRowHeight(25);
      tblDatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      jScrollPane1.setViewportView(tblDatos);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      try {
			// Datos
			String dni = txtDni.getText().trim();
			String apellido = txtApellidos.getText().trim();
			String nombre = txtNombres.getText().trim();
			// Proceso
			EmpleadoModel bean = new EmpleadoModel(nombre, apellido, dni);
			EmpleadoCrudController control = new EmpleadoCrudController();
			lista = control.read(bean);
			// Reporte
			mostrarLista();
		} catch (Exception e) {
			Mensaje.error(this, e.getMessage());
		}
   }//GEN-LAST:event_btnBuscarActionPerformed

   private void btnBuscar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar6ActionPerformed
      this.dispose();
   }//GEN-LAST:event_btnBuscar6ActionPerformed

   private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      EditarEmpleadoView view = new EditarEmpleadoView(null, true);
		view.setAccion(UtilView.CRUD_NUEVO);
		view.setRecord(new EmpleadoModel());
		Session.put("bean", null);
		view.setVisible(true);
		if(Session.get("bean") == null){
			return;
		}
		EmpleadoModel record = (EmpleadoModel) Session.get("bean");
		lista.set(0, record);
		mostrarLista();
   }//GEN-LAST:event_btnNuevoActionPerformed

   private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      if(lista.size() == 0){
			Mensaje.error(this, "No tienes datos en la tabla.");
			return;
		}
		int fila = tblDatos.getSelectedRow();
		if(fila == -1){
			Mensaje.error(this, "Debes seleccionar una fila.");
			return;
		}
		EditarEmpleadoView view = new EditarEmpleadoView(null, true);
		view.setAccion(UtilView.CRUD_EDITAR);
		view.setRecord(lista.get(fila));
		view.setVisible(true);
		if(Session.get("bean") == null){
			return;
		}
		EmpleadoModel record = (EmpleadoModel) Session.get("bean");
		lista.set(fila, record);
		mostrarLista();
   }//GEN-LAST:event_btnEditarActionPerformed

   private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
      if(lista.size() == 0){
			Mensaje.error(this, "No tienes datos en la tabla.");
			return;
		}
		int fila = tblDatos.getSelectedRow();
		if(fila == -1){
			Mensaje.error(this, "Debes seleccionar una fila.");
			return;
		}
		EditarEmpleadoView view = new EditarEmpleadoView(null, true);
		view.setAccion(UtilView.CRUD_ELIMINAR);
		view.setRecord(lista.get(fila));
		view.setVisible(true);
		if(Session.get("bean") == null){
			return;
		}
		lista.remove(fila);
		mostrarLista();
   }//GEN-LAST:event_btnBorrarActionPerformed

   private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
      if (lista == null || lista.isEmpty()) {
			return;
		}
		try {
			// Creación del libro
			String plantilla = "/plantillas/REPORTE-EMPLEADOS.xls";
			InputStream isPlantilla = getClass().getResourceAsStream(plantilla);
			POIFSFileSystem fs = new POIFSFileSystem(isPlantilla);
			HSSFWorkbook objLibro = new HSSFWorkbook(fs, true);
			// Crea la hoja
			HSSFSheet hoja = objLibro.getSheetAt(0);
			// Cargar los datos a la hoja
			int numFila = 3;
			HSSFRow objFila;
			for (EmpleadoModel model : lista) {
				numFila++;
				objFila = hoja.createRow(numFila);
				crearCeldaEntera(objFila, 0, model.getId());
				crearCeldaCadena(objFila, 1, model.getNombre());
				crearCeldaCadena(objFila, 2, model.getApellido());
				crearCeldaCadena(objFila, 3, model.getCorreo());
			}
			// Se vuelca la información a un archivo.
			FileOutputStream fileOut = new FileOutputStream("E://Archivos//EMPLEADOS.xls");
			objLibro.write(fileOut);
			fileOut.close();
			System.out.println("Todo ok.");
		} catch (Exception e) {
			e.printStackTrace();
		}
   }//GEN-LAST:event_btnExcelActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnBorrar;
   private javax.swing.JButton btnBuscar;
   private javax.swing.JButton btnBuscar6;
   private javax.swing.JButton btnEditar;
   private javax.swing.JButton btnExcel;
   private javax.swing.JButton btnNuevo;
   private javax.swing.JButton btnPDF;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tblDatos;
   private javax.swing.JTextField txtApellidos;
   private javax.swing.JTextField txtDni;
   private javax.swing.JTextField txtNombres;
   // End of variables declaration//GEN-END:variables

	private void mostrarLista() {
		// TableModel
		DefaultTableModel tabla = (DefaultTableModel) tblDatos.getModel();
		// Limpiar tabla
		tabla.setRowCount(0);
		// Cargar tabla con lista de datos
		for (EmpleadoModel bean : lista) {
			Object[] rowData = {
				bean.getId(), bean.getApellido(), bean.getNombre(),
				bean.getDni(), bean.getTelefono(), bean.getCorreo()
			};
			tabla.addRow(rowData);
		}
	}
	
	
	// Creación de celdas
	private void crearCeldaCadena(HSSFRow fila, int columna, String dato) {
		HSSFCell celda = fila.createCell(columna, CellType.STRING);
		celda.setCellValue(dato);
	}

	private void crearCeldaEntera(HSSFRow fila, int columna, int dato) {
		HSSFCell celda = fila.createCell(columna, CellType.NUMERIC);
		HSSFCellStyle style = fila.getSheet().getWorkbook().createCellStyle();
		style.setDataFormat(HSSFDataFormat.getBuiltinFormat("0"));
		celda.setCellStyle(style);
		celda.setCellValue(dato);
	}

	private void crearCeldaDecimal(HSSFRow fila, int columna, double dato) {
		HSSFCell celda = fila.createCell(columna, CellType.NUMERIC);
		HSSFCellStyle style = fila.getSheet().getWorkbook().createCellStyle();
		style.setDataFormat(HSSFDataFormat.getBuiltinFormat("#,##0.00"));
		celda.setCellStyle(style);
		celda.setCellValue(dato);
	}
}
