

DROP TABLE dbo.CLIENTE
go



DROP TABLE dbo.RUTA
go



DROP TABLE dbo.EMPLEADO
go



DROP TABLE dbo.ROL
go



DROP TABLE dbo.CIUDAD
go



CREATE TABLE dbo.CIUDAD
( 
	IDCIUDAD             integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(150)  NOT NULL ,
	DISTANCIA            integer  NOT NULL ,
	TIEMPO_VIAJE         integer  NULL ,
	CONSTRAINT XPKCIUDAD PRIMARY KEY (IDCIUDAD ASC)
)
go



CREATE TABLE dbo.ROL
( 
	IDROL                integer  NOT NULL ,
	NOMBRE               varchar(100)  NOT NULL ,
	CONSTRAINT XPKROL PRIMARY KEY (IDROL ASC)
)
go



CREATE TABLE dbo.EMPLEADO
( 
	IDEMPLEADO           integer  NOT NULL ,
	NOMBRE               varchar(100)  NOT NULL ,
	APELLIDO             varchar(100)  NOT NULL ,
	DNI                  varchar(20)  NOT NULL ,
	TELEFONO             varchar(20)  NOT NULL ,
	CORREO               varchar(100)  NOT NULL ,
	IDROL                integer  NOT NULL ,
	USUARIO              varchar(20)  NOT NULL ,
	CLAVE                varchar(20)  NOT NULL ,
	CONSTRAINT XPKEMPLEADO PRIMARY KEY (IDEMPLEADO ASC),
	CONSTRAINT U_EMPLEADO_USUARIO UNIQUE (USUARIO  ASC),
	CONSTRAINT FK_EMPLEADO_ROL FOREIGN KEY (IDROL) REFERENCES dbo.ROL(IDROL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go



CREATE TABLE dbo.RUTA
( 
	IDRUTA               integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(150)  NOT NULL ,
	ORIGEN               integer  NULL ,
	DESTINO              integer  NULL ,
	PISO1PRECIO1         integer  NULL ,
	PISO1PRECIO2         integer  NULL ,
	PISO2PRECIO1         integer  NULL ,
	PISO2PRECIO2         integer  NULL ,
	IDEMPLEADO           integer  NULL ,
	CONSTRAINT XPKRUTA PRIMARY KEY (IDRUTA ASC),
	CONSTRAINT FK_RUTA_CIUDAD_ORIGEN FOREIGN KEY (ORIGEN) REFERENCES dbo.CIUDAD(IDCIUDAD)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_RUTA_CIUDAD_DESTINO FOREIGN KEY (DESTINO) REFERENCES dbo.CIUDAD(IDCIUDAD)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_RUTA_EMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES dbo.EMPLEADO(IDEMPLEADO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go



CREATE TABLE dbo.CLIENTE
( 
	IDCLIENTE            integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(100)  NOT NULL ,
	APELLIDO             varchar(100)  NOT NULL ,
	DNI                  varchar(20)  NOT NULL ,
	TELEFONO             varchar(20)  NOT NULL ,
	CORREO               varchar(100)  NOT NULL ,
	CONSTRAINT XPKCLIENTE PRIMARY KEY (IDCLIENTE ASC)
)
go



