
DROP TABLE dbo.VENTA
go



DROP TABLE dbo.CLIENTE
go



DROP TABLE dbo.PROGRAMACION
go



DROP TABLE dbo.BUS
go



DROP TABLE dbo.RUTA
go



DROP TABLE dbo.EMPLEADO
go



DROP TABLE dbo.ROL
go



DROP TABLE dbo.CIUDAD
go



CREATE TABLE dbo.CIUDAD
( 
	IDCIUDAD             integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(150)  NOT NULL ,
	DISTANCIA            integer  NOT NULL ,
	TIEMPO_VIAJE         integer  NULL ,
	CONSTRAINT XPKCIUDAD PRIMARY KEY (IDCIUDAD ASC)
)
go



CREATE TABLE dbo.ROL
( 
	IDROL                integer  NOT NULL ,
	NOMBRE               varchar(100)  NOT NULL ,
	CONSTRAINT XPKROL PRIMARY KEY (IDROL ASC)
)
go



CREATE TABLE dbo.EMPLEADO
( 
	IDEMPLEADO           integer  NOT NULL ,
	NOMBRE               varchar(100)  NOT NULL ,
	APELLIDO             varchar(100)  NOT NULL ,
	DNI                  varchar(20)  NOT NULL ,
	TELEFONO             varchar(20)  NOT NULL ,
	CORREO               varchar(100)  NOT NULL ,
	IDROL                integer  NOT NULL ,
	USUARIO              varchar(20)  NOT NULL ,
	CLAVE                varchar(20)  NOT NULL ,
	CONSTRAINT XPKEMPLEADO PRIMARY KEY (IDEMPLEADO ASC),
	CONSTRAINT U_EMPLEADO_USUARIO UNIQUE (USUARIO  ASC),
	CONSTRAINT FK_EMPLEADO_ROL FOREIGN KEY (IDROL) REFERENCES dbo.ROL(IDROL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go



CREATE TABLE dbo.RUTA
( 
	IDRUTA               integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(150)  NOT NULL ,
	ORIGEN               integer  NULL ,
	DESTINO              integer  NULL ,
	PISO1PRECIO1         integer  NULL ,
	PISO1PRECIO2         integer  NULL ,
	PISO2PRECIO1         integer  NULL ,
	PISO2PRECIO2         integer  NULL ,
	IDEMPLEADO           integer  NULL ,
	CONSTRAINT XPKRUTA PRIMARY KEY (IDRUTA ASC),
	CONSTRAINT FK_RUTA_CIUDAD_ORIGEN FOREIGN KEY (ORIGEN) REFERENCES dbo.CIUDAD(IDCIUDAD)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_RUTA_CIUDAD_DESTINO FOREIGN KEY (DESTINO) REFERENCES dbo.CIUDAD(IDCIUDAD)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_RUTA_EMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES dbo.EMPLEADO(IDEMPLEADO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go



CREATE TABLE dbo.BUS
( 
	IDBUS                integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(150)  NOT NULL ,
	PISO1ASIENTOSPRECIO1 integer  NOT NULL ,
	PISO1ASIENTOSPRECIO2 integer  NOT NULL ,
	PISO2ASIENTOSPRECIO1 integer  NOT NULL ,
	PISO2ASIENTOSPRECIO2 integer  NOT NULL ,
	CONSTRAINT XPKBUS PRIMARY KEY (IDBUS ASC)
)
go



CREATE TABLE dbo.PROGRAMACION
( 
	IDPROGRAMACION       integer IDENTITY ( 1,1 ) ,
	IDRUTA               integer  NULL ,
	IDBUS                integer  NULL ,
	IDEMPLEADO           integer  NULL ,
	FECHASALIDA          datetime  NOT NULL ,
	HORASALIDA           varchar(20)  NOT NULL ,
	FECHALLEGADA         datetime  NOT NULL ,
	HORALLEGADA          varchar(20)  NOT NULL ,
	PISO1PRECIO1         numeric(10,2)  NOT NULL ,
	PISO1PRECIO2         numeric(10,2)  NOT NULL ,
	PISO2PRECIO1         numeric(10,2)  NOT NULL ,
	PISO2PRECIO2         numeric(10,2)  NOT NULL ,
	PISO1ASIENTOSPRECIO1 integer  NOT NULL ,
	PISO1ASIENTOSPRECIO2 integer  NOT NULL ,
	PISO2ASIENTOSPRECIO1 integer  NOT NULL ,
	PISO2ASIENTOSPRECIO2 integer  NOT NULL ,
	CONSTRAINT XPKPROGRAMACION PRIMARY KEY (IDPROGRAMACION ASC),
	CONSTRAINT R_12 FOREIGN KEY (IDRUTA) REFERENCES dbo.RUTA(IDRUTA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT R_13 FOREIGN KEY (IDBUS) REFERENCES dbo.BUS(IDBUS)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT R_14 FOREIGN KEY (IDEMPLEADO) REFERENCES dbo.EMPLEADO(IDEMPLEADO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go



CREATE TABLE dbo.CLIENTE
( 
	IDCLIENTE            integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(100)  NOT NULL ,
	APELLIDO             varchar(100)  NOT NULL ,
	DNI                  varchar(20)  NOT NULL ,
	TELEFONO             varchar(20)  NOT NULL ,
	CORREO               varchar(100)  NOT NULL ,
	CONSTRAINT XPKCLIENTE PRIMARY KEY (IDCLIENTE ASC)
)
go



CREATE TABLE dbo.VENTA
( 
	IDVENTA              integer IDENTITY ( 1,1 ) ,
	IDCLIENTE            integer  NOT NULL ,
	FECHA_REGISTRO       datetime  NOT NULL ,
	FECHA_PAGO           datetime  NULL ,
	VENDEDOR             integer  NOT NULL ,
	CAJA                 integer  NULL ,
	IMPORTE              numeric(10,2)  NOT NULL ,
	IMPUESTO             numeric(10,2)  NOT NULL ,
	TOTAL                numeric(10,2)  NOT NULL ,
	ESTADO               integer  NOT NULL ,
	CONSTRAINT XPKVENTA PRIMARY KEY (IDVENTA ASC),
	CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES dbo.CLIENTE(IDCLIENTE)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_VENTA_EMPLEADO_VENDEDOR FOREIGN KEY (VENDEDOR) REFERENCES dbo.EMPLEADO(IDEMPLEADO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_VENTA_EMPLEADO_CAJA FOREIGN KEY (CAJA) REFERENCES dbo.EMPLEADO(IDEMPLEADO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go