
ALTER PROCEDURE USP_REPO_COMISON
(@ANIO INT, @MES INT)
AS
BEGIN
	WITH 
	V1 AS (
		SELECT VENDEDOR, SUM(IMPORTE) VENTAS
		FROM VENTA 
		WHERE ESTADO = 2
		AND YEAR(FECHA_PAGO) = @ANIO 
		AND MONTH(FECHA_PAGO) = @MES
		GROUP BY VENDEDOR )
	SELECT 
		@ANIO ANIO, @MES MES, V1.VENDEDOR, 
		CONCAT(E.NOMBRE,', ',E.APELLIDO) NOMBRE,V1.VENTAS,
		CAST(V1.VENTAS * 0.05 AS DECIMAL(12,2)) COMISION,
		GETDATE() FECHAREPORTE
	FROM EMPLEADO E 
	JOIN V1 ON E.IDEMPLEADO = V1.VENDEDOR
END;
GO

EXEC USP_REPO_COMISON 2021,12
GO



