/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pe.edu.uni.sisteventasapp.view;

import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import pe.edu.uni.sisteventasapp.controller.ConsultaController;
import pe.edu.uni.sisteventasapp.util.Mensaje;


/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class ConsultaComisionView extends javax.swing.JInternalFrame {

	private List<Map<String,?>> listaData;
	private ConsultaController consultaController;

	/**
	 * Creates new form MantClientesView
	 */
	public ConsultaComisionView() {
		initComponents();
		listaData = new ArrayList<>();
		consultaController = new ConsultaController();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtAnio = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtMes = new javax.swing.JTextField();
      btnConsultar = new javax.swing.JButton();
      btnExcel = new javax.swing.JButton();
      jButton6 = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      tablaDatos = new javax.swing.JTable();

      setClosable(true);
      setMaximizable(true);
      setTitle("Mantenimiento de clientes");
      setToolTipText("Mantenimiento de clientes.");

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(153, 153, 153));
      jLabel1.setText("Año");

      txtAnio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtAnio.setForeground(new java.awt.Color(153, 153, 153));

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(153, 153, 153));
      jLabel2.setText("Mes");

      txtMes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtMes.setForeground(new java.awt.Color(153, 153, 153));

      btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
      btnConsultar.setToolTipText("Buscar clientes");
      btnConsultar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnConsultarActionPerformed(evt);
         }
      });

      btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.png"))); // NOI18N
      btnExcel.setToolTipText("Buscar clientes");
      btnExcel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnExcelActionPerformed(evt);
         }
      });

      jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pdf.png"))); // NOI18N
      jButton6.setToolTipText("Buscar clientes");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
               .addComponent(txtAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(txtMes, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
            .addGap(28, 28, 28)
            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(0, 0, Short.MAX_VALUE))
               .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N

      tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "AÑO", "MES", "CODIGO", "NOMBRE", "VENTAS", "COMISION"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
         };
         boolean[] canEdit = new boolean [] {
            false, false, true, false, false, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      tablaDatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      jScrollPane1.setViewportView(tablaDatos);
      if (tablaDatos.getColumnModel().getColumnCount() > 0) {
         tablaDatos.getColumnModel().getColumn(0).setResizable(false);
         tablaDatos.getColumnModel().getColumn(1).setResizable(false);
         tablaDatos.getColumnModel().getColumn(3).setResizable(false);
         tablaDatos.getColumnModel().getColumn(4).setResizable(false);
      }

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1264, Short.MAX_VALUE)
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
		try {
			// Datos
			Integer anio = Integer.parseInt(txtAnio.getText());
			Integer mes = Integer.parseInt(txtMes.getText());
			// Ejecutar consulta
			listaData = consultaController.consultaComision(anio, mes);
			// Mostrar lista en la tabla
			pintarTabla(0);
		} catch (Exception e) {
			Mensaje.error(this, title);
		}
   }//GEN-LAST:event_btnConsultarActionPerformed

   private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
      if (listaData == null || listaData.isEmpty()) {
			Mensaje.error(rootPane, "No hay datos que exportar.");
			return;
		}
		String archivo = Mensaje.showSelectExcelFile(rootPane);
		if (archivo.isEmpty()) {
			return;
		}
		try {
			// El libro
			String plantilla = "/plantillas/INFORME-COMISION-X-EMPLEADO.xls";
			//InputStream isPlantilla = Class.class.getResourceAsStream(plantilla);
			InputStream is = getClass().getResourceAsStream(plantilla);
			POIFSFileSystem fs = new POIFSFileSystem(is);
			HSSFWorkbook wb = new HSSFWorkbook(fs, true); // Crea una copia de la plantilla en memoria
			// Acceder a la hoja
			HSSFSheet sheet = wb.getSheetAt(0);
			// Llenar datos
			int fila = 6;
			for (Map<String,?> bean : listaData) {
				fila++;
				HSSFRow row = sheet.createRow(fila);
				row.createCell(0).setCellValue(bean.get("VENDEDOR").toString());
				row.createCell(1).setCellValue(bean.get("NOMBRE").toString());
				row.createCell(2).setCellValue(bean.get("VENTAS").toString());
				row.createCell(3).setCellValue(bean.get("COMISION").toString());
			}
			// Grabar
			FileOutputStream fileOut = new FileOutputStream(archivo);
			wb.write(fileOut);
			fileOut.close();
			Mensaje.info(rootPane, "Proceso ok.");
		} catch (Exception e) {
			e.printStackTrace();
			Mensaje.error(rootPane, e.getMessage());
		}
   }//GEN-LAST:event_btnExcelActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnConsultar;
   private javax.swing.JButton btnExcel;
   private javax.swing.JButton jButton6;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tablaDatos;
   private javax.swing.JTextField txtAnio;
   private javax.swing.JTextField txtMes;
   // End of variables declaration//GEN-END:variables

	private void pintarTabla(int filaActiva) {
		DefaultTableModel tabla;
		tabla = (DefaultTableModel) tablaDatos.getModel();
		tabla.setRowCount(0);
		for (Map<String,?> rec : listaData) {
			Object[] rowData = new Object[]{rec.get("ANIO"), rec.get("MES"),
				rec.get("VENDEDOR"),rec.get("NOMBRE"),rec.get("VENTAS"),
				rec.get("COMISION")};
			tabla.addRow(rowData);
		}
		if(filaActiva>=listaData.size() || filaActiva<0){
			return;
		}
		tablaDatos.setRowSelectionInterval(filaActiva, filaActiva);
	}

}
