package pe.edu.uni.sisteventasapp.view;

import pe.edu.uni.sisteventasapp.controller.ClienteController;
import pe.edu.uni.sisteventasapp.dto.ClienteDto;
import pe.edu.uni.sisteventasapp.util.Mensaje;
import pe.edu.uni.sisteventasapp.util.Session;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class EditarClienteView extends javax.swing.JDialog {

	private String accion;
	private ClienteDto bean;

	/**
	 * Creates new form EditarClienteView
	 */
	public EditarClienteView(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.setLocationRelativeTo(null);
		accion = "";
		bean = null;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtId = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtApellido = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      txtNombre = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      txtDni = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      txtTelefono = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      txtCorreo = new javax.swing.JTextField();
      jPanel2 = new javax.swing.JPanel();
      btnGrabar = new javax.swing.JButton();
      btnCancelar = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
      setTitle("[accion] CLIENTE");

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N
      jPanel1.setLayout(new java.awt.GridLayout(6, 3));

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel1.setText("ID CLIENTE");
      jPanel1.add(jLabel1);

      txtId.setColumns(2);
      txtId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtId.setDisabledTextColor(new java.awt.Color(0, 153, 255));
      txtId.setEnabled(false);
      jPanel1.add(txtId);

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel2.setText("APELLIDO");
      jPanel1.add(jLabel2);

      txtApellido.setColumns(2);
      txtApellido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtApellido.setDisabledTextColor(new java.awt.Color(0, 153, 255));
      jPanel1.add(txtApellido);

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel3.setText("NOMBRE");
      jPanel1.add(jLabel3);

      txtNombre.setColumns(2);
      txtNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtNombre.setDisabledTextColor(new java.awt.Color(0, 153, 255));
      jPanel1.add(txtNombre);

      jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel4.setText("DNI");
      jPanel1.add(jLabel4);

      txtDni.setColumns(2);
      txtDni.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtDni.setDisabledTextColor(new java.awt.Color(0, 153, 255));
      jPanel1.add(txtDni);

      jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel5.setText("TELEFONO");
      jPanel1.add(jLabel5);

      txtTelefono.setColumns(2);
      txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtTelefono.setDisabledTextColor(new java.awt.Color(0, 153, 255));
      jPanel1.add(txtTelefono);

      jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel6.setText("CORREO");
      jPanel1.add(jLabel6);

      txtCorreo.setColumns(2);
      txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtCorreo.setDisabledTextColor(new java.awt.Color(0, 153, 255));
      jPanel1.add(txtCorreo);

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N
      jPanel2.setLayout(new java.awt.GridLayout(1, 2));

      btnGrabar.setBackground(new java.awt.Color(153, 255, 255));
      btnGrabar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
      btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grabar.png"))); // NOI18N
      btnGrabar.setText("Aceptar");
      btnGrabar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnGrabarActionPerformed(evt);
         }
      });
      jPanel2.add(btnGrabar);

      btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
      btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
      btnCancelar.setText("Cancelar");
      btnCancelar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelarActionPerformed(evt);
         }
      });
      jPanel2.add(btnCancelar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(10, 10, 10)
                  .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE))
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      Session.put("RESPUESTA", UtilView.MODAL_CANCELAR);
		this.dispose();
   }//GEN-LAST:event_btnCancelarActionPerformed

   private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
      try {
			// Datos
			ClienteDto bean = new ClienteDto();
			bean.setIdcliente(Integer.parseInt(txtId.getText()));
			bean.setApellido(txtApellido.getText());
			bean.setNombre(txtNombre.getText());
			bean.setDni(txtDni.getText());
			bean.setTelefono(txtTelefono.getText());
			bean.setCorreo(txtCorreo.getText());
			// Proceso
			ClienteController controller = new ClienteController();
			controller.procesar(accion, bean);
			Mensaje.info(this, "Proceso ejecutado correctamente.");
			Session.put("RESPUESTA", UtilView.MODAL_ACEPTAR);
			Session.put("BEAN", bean);
			this.dispose();
		} catch (Exception e) {
			Mensaje.error(this, e.getMessage());
		}
   }//GEN-LAST:event_btnGrabarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditarClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditarClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditarClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditarClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				EditarClienteView dialog = new EditarClienteView(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCancelar;
   private javax.swing.JButton btnGrabar;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JTextField txtApellido;
   private javax.swing.JTextField txtCorreo;
   private javax.swing.JTextField txtDni;
   private javax.swing.JTextField txtId;
   private javax.swing.JTextField txtNombre;
   private javax.swing.JTextField txtTelefono;
   // End of variables declaration//GEN-END:variables

	public void prepararFormulario() {
		accion = Session.get("ACCION").toString();
		this.setTitle(accion + " CLIENTE");
		mostrarBean();
		switch (accion) {
			case UtilView.CRUD_CREATE:
				btnGrabar.setText("Crear");
				habilitarFormulario(true);
				break;
			case UtilView.CRUD_UPDATE:
				btnGrabar.setText("Actualizar");
				habilitarFormulario(true);
				break;
			case UtilView.CRUD_DELETE:
				habilitarFormulario(false);
				btnGrabar.setText("Eliminar");
				break;
		}
		
	}

	private void habilitarFormulario(boolean estado){
		txtApellido.setEnabled(estado);
		txtNombre.setEnabled(estado);
		txtDni.setEnabled(estado);
		txtTelefono.setEnabled(estado);
		txtCorreo.setEnabled(estado);
	}
	
	private void mostrarBean() {
		bean = (ClienteDto) Session.get("BEAN");
		txtId.setText("" + bean.getIdcliente());
		txtApellido.setText(bean.getApellido());
		txtNombre.setText(bean.getNombre());
		txtDni.setText(bean.getDni());
		txtTelefono.setText(bean.getTelefono());
		txtCorreo.setText(bean.getCorreo());
	}

}
