package pe.edu.uni.sisteventasapp.view;

import javax.swing.JInternalFrame;
import pe.edu.uni.sisteventasapp.dto.EmpleadoDto;
import pe.edu.uni.sisteventasapp.util.Session;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class MainFormView extends javax.swing.JFrame {

	public MainFormView() {
		initComponents();
		establecerTitulo();
		activarMenu();
	}

	private void establecerTitulo() {
		EmpleadoDto dto = (EmpleadoDto) Session.get("USUARIO");
		String titulo = "SISTEMA DE VENTAS ( Usuario: " + dto.getUsuario() + " )";
		this.setTitle(titulo);
		this.setLocationRelativeTo(null);
		this.setExtendedState(MAXIMIZED_BOTH);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      desktopPane = new javax.swing.JDesktopPane();
      menuBar = new javax.swing.JMenuBar();
      menuArchivo = new javax.swing.JMenu();
      menuArchivoSalir = new javax.swing.JMenuItem();
      menuProcesos = new javax.swing.JMenu();
      menuProcesosRegistrarVenta = new javax.swing.JMenuItem();
      menuProcesosEjecutarVenta = new javax.swing.JMenuItem();
      menuProcesosCancelarVenta = new javax.swing.JMenuItem();
      menuTablas = new javax.swing.JMenu();
      menuTablasClientes = new javax.swing.JMenuItem();
      menuConsultas = new javax.swing.JMenu();
      menuConsultasComiisión = new javax.swing.JMenuItem();
      menuReportes = new javax.swing.JMenu();
      menuUtil = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      menuArchivo.setText("Archivo");

      menuArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
      menuArchivoSalir.setText("Salir");
      menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuArchivoSalirActionPerformed(evt);
         }
      });
      menuArchivo.add(menuArchivoSalir);

      menuBar.add(menuArchivo);

      menuProcesos.setText("Procesos");

      menuProcesosRegistrarVenta.setText("Registrar venta");
      menuProcesosRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuProcesosRegistrarVentaActionPerformed(evt);
         }
      });
      menuProcesos.add(menuProcesosRegistrarVenta);

      menuProcesosEjecutarVenta.setText("Ejecutar venta");
      menuProcesos.add(menuProcesosEjecutarVenta);

      menuProcesosCancelarVenta.setText("Cancelar venta");
      menuProcesos.add(menuProcesosCancelarVenta);

      menuBar.add(menuProcesos);

      menuTablas.setText("Tablas");

      menuTablasClientes.setText("Clientes");
      menuTablasClientes.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuTablasClientesActionPerformed(evt);
         }
      });
      menuTablas.add(menuTablasClientes);

      menuBar.add(menuTablas);

      menuConsultas.setText("Consultas");

      menuConsultasComiisión.setText("Comisiones");
      menuConsultasComiisión.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuConsultasComiisiónActionPerformed(evt);
         }
      });
      menuConsultas.add(menuConsultasComiisión);

      menuBar.add(menuConsultas);

      menuReportes.setText("Reportes");
      menuBar.add(menuReportes);

      menuUtil.setText("Util");
      menuBar.add(menuUtil);

      setJMenuBar(menuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
            .addGap(0, 0, 0))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
      System.exit(0);
   }//GEN-LAST:event_menuArchivoSalirActionPerformed

   private void menuTablasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasClientesActionPerformed
      mostrarForm(MantClientesView.class);
   }//GEN-LAST:event_menuTablasClientesActionPerformed

   private void menuProcesosRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosRegistrarVentaActionPerformed
      mostrarForm(ProcesoRegistrarVentaView.class);
   }//GEN-LAST:event_menuProcesosRegistrarVentaActionPerformed

   private void menuConsultasComiisiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasComiisiónActionPerformed
      mostrarForm(ConsultaComisionView.class);
   }//GEN-LAST:event_menuConsultasComiisiónActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFormView().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JDesktopPane desktopPane;
   private javax.swing.JMenu menuArchivo;
   private javax.swing.JMenuItem menuArchivoSalir;
   private javax.swing.JMenuBar menuBar;
   private javax.swing.JMenu menuConsultas;
   private javax.swing.JMenuItem menuConsultasComiisión;
   private javax.swing.JMenu menuProcesos;
   private javax.swing.JMenuItem menuProcesosCancelarVenta;
   private javax.swing.JMenuItem menuProcesosEjecutarVenta;
   private javax.swing.JMenuItem menuProcesosRegistrarVenta;
   private javax.swing.JMenu menuReportes;
   private javax.swing.JMenu menuTablas;
   private javax.swing.JMenuItem menuTablasClientes;
   private javax.swing.JMenu menuUtil;
   // End of variables declaration//GEN-END:variables

	private void mostrarForm(Class<?> aClass) {
		try {
			// Variable de control
			JInternalFrame view = null;
			// Buscar instancia
			for (JInternalFrame form : desktopPane.getAllFrames()) {
				if (aClass.isInstance(form)) {
					view = form;
					break;
				}
			}
			// Crear instancia
			if (view == null) {
				view = (JInternalFrame) aClass.getConstructor().newInstance();
				desktopPane.add(view);
				view.setVisible(true);
			}
			view.setMaximum(true);
			view.setSelected(true);
		} catch (Exception e) {
		}
	}

	private void activarMenu(){
		EmpleadoDto dto = (EmpleadoDto) Session.get("USUARIO");
		menuProcesosRegistrarVenta.setEnabled(dto.getIdrol()==1 || dto.getIdrol()==2);
		menuProcesosEjecutarVenta.setEnabled(dto.getIdrol()==1 || dto.getIdrol()==4);
		menuProcesosCancelarVenta.setEnabled(dto.getIdrol()==1 || dto.getIdrol()==2);
	}
}
