/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pe.edu.uni.sisteventasapp.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pe.edu.uni.sisteventasapp.controller.ClienteController;
import pe.edu.uni.sisteventasapp.dto.ClienteDto;
import pe.edu.uni.sisteventasapp.util.Mensaje;
import pe.edu.uni.sisteventasapp.util.Session;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class MantClientesView extends javax.swing.JInternalFrame {

	private List<ClienteDto> listaData;
	ClienteController clienteController;

	/**
	 * Creates new form MantClientesView
	 */
	public MantClientesView() {
		initComponents();
		listaData = new ArrayList<>();
		clienteController = new ClienteController();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtCodigo = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtApellido = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      txtNombre = new javax.swing.JTextField();
      btnConsultar = new javax.swing.JButton();
      btnNuevo = new javax.swing.JButton();
      btnEditar = new javax.swing.JButton();
      btnEliminar = new javax.swing.JButton();
      jButton5 = new javax.swing.JButton();
      jButton6 = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      tablaDatos = new javax.swing.JTable();

      setClosable(true);
      setMaximizable(true);
      setTitle("Mantenimiento de clientes");
      setToolTipText("Mantenimiento de clientes.");

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(153, 153, 153));
      jLabel1.setText("Código");

      txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtCodigo.setForeground(new java.awt.Color(153, 153, 153));

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(153, 153, 153));
      jLabel2.setText("Apellido");

      txtApellido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtApellido.setForeground(new java.awt.Color(153, 153, 153));

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(153, 153, 153));
      jLabel3.setText("Nombre");

      txtNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtNombre.setForeground(new java.awt.Color(153, 153, 153));

      btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
      btnConsultar.setToolTipText("Buscar clientes");
      btnConsultar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnConsultarActionPerformed(evt);
         }
      });

      btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
      btnNuevo.setToolTipText("Buscar clientes");
      btnNuevo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnNuevoActionPerformed(evt);
         }
      });

      btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
      btnEditar.setToolTipText("Buscar clientes");
      btnEditar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEditarActionPerformed(evt);
         }
      });

      btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tacho.png"))); // NOI18N
      btnEliminar.setToolTipText("Buscar clientes");
      btnEliminar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEliminarActionPerformed(evt);
         }
      });

      jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.png"))); // NOI18N
      jButton5.setToolTipText("Buscar clientes");

      jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pdf.png"))); // NOI18N
      jButton6.setToolTipText("Buscar clientes");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
               .addComponent(txtCodigo))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(txtApellido)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(txtNombre)
               .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(0, 0, Short.MAX_VALUE))
               .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N

      tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "CODIGO", "APELLIDO", "NOMBRE", "DNI", "TELEFONO", "CORREO"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
         };
         boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      tablaDatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      jScrollPane1.setViewportView(tablaDatos);
      if (tablaDatos.getColumnModel().getColumnCount() > 0) {
         tablaDatos.getColumnModel().getColumn(0).setResizable(false);
         tablaDatos.getColumnModel().getColumn(1).setResizable(false);
         tablaDatos.getColumnModel().getColumn(2).setResizable(false);
         tablaDatos.getColumnModel().getColumn(3).setResizable(false);
         tablaDatos.getColumnModel().getColumn(5).setResizable(false);
      }

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
		try {
			// Datos
			ClienteDto bean = new ClienteDto();
			if (txtCodigo.getText().length() > 0) {
				bean.setIdcliente(Integer.parseInt(txtCodigo.getText()));
			}
			bean.setApellido(txtApellido.getText());
			bean.setNombre(txtNombre.getText());
			// Traer lista de clientes
			listaData = clienteController.read(bean);
			// Mostrar lista en la tabla
			pintarTabla(0);
		} catch (Exception e) {
			Mensaje.error(this, title);
		}
   }//GEN-LAST:event_btnConsultarActionPerformed

   private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
		Session.put("ACCION", UtilView.CRUD_CREATE);
		ClienteDto bean = new ClienteDto();
		Session.put("BEAN", bean);
		EditarClienteView view = new EditarClienteView(null, true);
		view.prepararFormulario();
		view.setVisible(true);
		String respuesta = Session.get("RESPUESTA").toString();
		if (respuesta.equals(UtilView.MODAL_CANCELAR)) {
			return;
		}
		bean = (ClienteDto) Session.get("BEAN");
		listaData.add(bean);
		pintarTabla(listaData.size()-1);
   }//GEN-LAST:event_btnNuevoActionPerformed

   private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
		int fila = tablaDatos.getSelectedRow();
		if (fila == -1) {
			Mensaje.error(this, "Debe seleccionar una fila.");
			return;
		}
		ClienteDto bean = listaData.get(fila);
		Session.put("BEAN", bean);
		Session.put("ACCION", UtilView.CRUD_UPDATE);
		EditarClienteView view = new EditarClienteView(null, true);
		view.prepararFormulario();
		view.setVisible(true);
		String respuesta = Session.get("RESPUESTA").toString();
		if (respuesta.equals(UtilView.MODAL_CANCELAR)) {
			return;
		}
		bean = (ClienteDto) Session.get("BEAN");
		listaData.set(fila, bean);
		pintarTabla(fila);
   }//GEN-LAST:event_btnEditarActionPerformed

   private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
		int fila = tablaDatos.getSelectedRow();
		if (fila == -1) {
			Mensaje.error(this, "Debe seleccionar una fila.");
			return;
		}
		ClienteDto bean = listaData.get(fila);
		Session.put("BEAN", bean);
		Session.put("ACCION", UtilView.CRUD_DELETE);
		EditarClienteView view = new EditarClienteView(null, true);
		view.prepararFormulario();
		view.setVisible(true);
		String respuesta = Session.get("RESPUESTA").toString();
		if (respuesta.equals(UtilView.MODAL_CANCELAR)) {
			return;
		}
		listaData.remove(fila);
		if(listaData.size()==0){
			fila = -1;
		}else if(fila>=listaData.size()){
			fila = listaData.size()-1;
		}
		pintarTabla(fila);
   }//GEN-LAST:event_btnEliminarActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnConsultar;
   private javax.swing.JButton btnEditar;
   private javax.swing.JButton btnEliminar;
   private javax.swing.JButton btnNuevo;
   private javax.swing.JButton jButton5;
   private javax.swing.JButton jButton6;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tablaDatos;
   private javax.swing.JTextField txtApellido;
   private javax.swing.JTextField txtCodigo;
   private javax.swing.JTextField txtNombre;
   // End of variables declaration//GEN-END:variables

	private void pintarTabla(int filaActiva) {
		DefaultTableModel tabla;
		tabla = (DefaultTableModel) tablaDatos.getModel();
		tabla.setRowCount(0);
		for (ClienteDto rec : listaData) {
			Object[] rowData = new Object[]{rec.getIdcliente(), rec.getApellido(), rec.getNombre(),
				rec.getDni(), rec.getTelefono(), rec.getCorreo()};
			tabla.addRow(rowData);
		}
		if(filaActiva>=listaData.size() || filaActiva<0){
			return;
		}
		tablaDatos.setRowSelectionInterval(filaActiva, filaActiva);
	}

}
