package pe.edu.uni.sisteventasapp.view;

import java.util.List;
import pe.edu.uni.sisteventasapp.controller.VentaController;
import pe.edu.uni.sisteventasapp.dto.AutoDto;
import pe.edu.uni.sisteventasapp.dto.ClienteDto;
import pe.edu.uni.sisteventasapp.dto.ComboDto;
import pe.edu.uni.sisteventasapp.dto.EmpleadoDto;
import pe.edu.uni.sisteventasapp.dto.VentaDto;
import pe.edu.uni.sisteventasapp.util.Mensaje;
import pe.edu.uni.sisteventasapp.util.Session;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class ProcesoRegistrarVentaView extends javax.swing.JInternalFrame {
	
	private VentaController ventaController;

    /** Creates new form ProcesoRegistrarVentaView */
    public ProcesoRegistrarVentaView() {
        initComponents();
		  ventaController = new VentaController();
		  cargarComboClientes();
		  cargarComboMarcas();
		  mostrarEmpleado();
    }
	 
	 private void mostrarEmpleado(){
		 EmpleadoDto bean = (EmpleadoDto) Session.get("USUARIO");
		 txtVendedor.setText(bean.getNombre() + ", " + bean.getApellido());
	 }
	 
	 private void cargarComboMarcas(){
		 try {
			 List<ComboDto> lista = ventaController.obtenerMarcas();
			 cboMarca.removeAllItems();
			 for (ComboDto bean : lista) {
				 cboMarca.addItem(bean);
			 }
			 cboMarca.setSelectedIndex(-1);
		 } catch (Exception e) {
		 }
	 }
	 
	 private void cargarComboClientes(){
		 try {
			 List<ComboDto> lista = ventaController.obtenerClientes();
			 cboCliente.removeAllItems();
			 for (ComboDto bean : lista) {
				 cboCliente.addItem(bean);
			 }
			 cboCliente.setSelectedIndex(-1);
		 } catch (Exception e) {
		 }
	 }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      btnGrabar = new javax.swing.JButton();
      btnCancelar = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtVendedor = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      txtColor = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      txtPrecio = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      cboAuto = new javax.swing.JComboBox<>();
      cboCliente = new javax.swing.JComboBox<>();
      cboMarca = new javax.swing.JComboBox<>();

      setClosable(true);
      setMaximizable(true);
      setTitle("REGISTRAR VENTA");

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N

      btnGrabar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
      btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grabar.png"))); // NOI18N
      btnGrabar.setText("Grabar");
      btnGrabar.setToolTipText("Registra la venta");
      btnGrabar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnGrabarActionPerformed(evt);
         }
      });

      btnCancelar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
      btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
      btnCancelar.setText("Cancelar");
      btnCancelar.setToolTipText("Cancela la operación.");
      btnCancelar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelarActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
               .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N

      jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
      jLabel1.setText("Vendedor");

      txtVendedor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
      txtVendedor.setDisabledTextColor(new java.awt.Color(0, 102, 204));
      txtVendedor.setEnabled(false);

      jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
      jLabel2.setText("Cliente");

      jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
      jLabel3.setText("Marca");

      jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
      jLabel4.setText("Automóvil");

      txtColor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
      txtColor.setDisabledTextColor(new java.awt.Color(0, 102, 204));
      txtColor.setEnabled(false);

      jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
      jLabel5.setText("Color");

      txtPrecio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
      txtPrecio.setDisabledTextColor(new java.awt.Color(0, 102, 204));
      txtPrecio.setEnabled(false);

      jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
      jLabel6.setText("Precio");

      cboAuto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
      cboAuto.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cboAutoActionPerformed(evt);
         }
      });

      cboCliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

      cboMarca.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
      cboMarca.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cboMarcaActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cboCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cboAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(371, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
               .addComponent(cboCliente))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
               .addComponent(cboMarca))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
               .addComponent(cboAuto))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtColor, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
            .addContainerGap(22, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
		try {
			// Variables
			VentaDto bean = new VentaDto();
			double importe, impuesto, total;
			// Datos
			ComboDto cliente = (ComboDto) cboCliente.getSelectedItem();
			ComboDto auto = (ComboDto) cboAuto.getSelectedItem();
			EmpleadoDto vendedor = (EmpleadoDto) Session.get("USUARIO");
			total = Double.parseDouble(txtPrecio.getText());
			importe = total / 1.18;
			impuesto = total - importe;			
			bean.setIdcliente(cliente.getCodigo());
			bean.setIdauto(auto.getCodigo());
			bean.setVendedor(vendedor.getIdempleado());
			bean.setEstado(1);
			bean.setImporte(importe);
			bean.setImpuesto(impuesto);
			bean.setTotal(total);
			// Grabar
			ventaController.grabarVenta(bean);
			// Mensaje
			Mensaje.info(this, "Proceso ejecutado correctamente.");
		} catch (Exception e) {
			Mensaje.error(this, e.getMessage());
		}
   }//GEN-LAST:event_btnGrabarActionPerformed

   private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
		this.dispose();
   }//GEN-LAST:event_btnCancelarActionPerformed

   private void cboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMarcaActionPerformed
      int index = cboMarca.getSelectedIndex();
		if(index == -1){
			return;
		}
		ComboDto marca = (ComboDto) cboMarca.getSelectedItem();
		List<ComboDto> autos = ventaController.obtenerAutosDisponibles(marca.getCodigo());
		txtColor.setText("");
		txtPrecio.setText("");
		cboAuto.setEnabled(false);
		cboAuto.removeAllItems();
		for (ComboDto auto : autos) {
			cboAuto.addItem(auto);
		}
		cboAuto.setSelectedIndex(-1);
		cboAuto.setEnabled(true);
   }//GEN-LAST:event_cboMarcaActionPerformed

   private void cboAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAutoActionPerformed
      txtColor.setText("");
		txtPrecio.setText("");
		int index = cboAuto.getSelectedIndex();
		if(index==-1){
			return;
		}
		ComboDto bean = (ComboDto) cboAuto.getSelectedItem();
		AutoDto autoDto = ventaController.traerAutoPorId(bean.getCodigo());
		txtColor.setText(autoDto.getColor());
		txtPrecio.setText("" + autoDto.getPrecio());
   }//GEN-LAST:event_cboAutoActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCancelar;
   private javax.swing.JButton btnGrabar;
   private javax.swing.JComboBox<ComboDto> cboAuto;
   private javax.swing.JComboBox<ComboDto> cboCliente;
   private javax.swing.JComboBox<ComboDto> cboMarca;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JTextField txtColor;
   private javax.swing.JTextField txtPrecio;
   private javax.swing.JTextField txtVendedor;
   // End of variables declaration//GEN-END:variables

}
